language: node_js
services:
  - postgresql
before_script:
  - psql -c 'create database menternship_test;' -U postgres
matrix:
  include:
    - node_js: "6"
sudo: required
dist: trusty
cache:
   directories:
     - node_modules
script:
  - npm run test-migrate up
  - npm test
