language: node_js
matrix:
  include:
    - node_js: "6"
sudo: required
dist: trusty
cache:
   directories:
     - node_modules
script:
  - npm run test-migrate up
  - npm test
  - npm run test-migrate down
